---
title: "RNAseq DCM Analysis LumA vs. LumB"
author: "Kevin O'Connor"
date: "7/25/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries and directories.
library(dplyr)
data.dir <- file.path("/Users/kevinoconnor/Documents/Research/DCM/Data/7_25_18")
```

This document contains diagnostics from running the DCM algorithm on RNAseq data with altered filtering including small mean removal, small variance removal, large zero count removal, and PC removal.

```{r dcm_5, echo=FALSE}
jacard <- function(a, b){
  length(intersect(a, b))/length(union(a, b))
}

# Get initial set.
load(file.path(data.dir, "pcft_Initialization.RData"))
init_set <- length(initialization$"found")

# Collect data from each search.
no_output <- lapply(1:2, function(i){
  # Load data from i'th search.
  load(file.path(data.dir, paste0("pcft_DCM_", i, ".RData")))
  
  # Iterate through consecutive sets and record intersections and jacards.
  tot_int <- DCM$it_sets[[1]]
  vals <- lapply(1:(length(DCM$it_sets)-1), function(j){
    # Store first and second sets.
    set_a <- DCM$it_sets[[j]]
    set_b <- DCM$it_sets[[j+1]]
    
    # Update total intersection.
    tot_int <- length(intersect(tot_int, set_b))
    
    # Return relevant information.
    if(j < (length(DCM$it_sets)-1)){
      return(list("intersect" = length(intersect(set_a, set_b)),
                  "jacard"    = jacard(set_a, set_b),
                  "set_sizes" = length(set_b)))
    } else {
      return(list("intersect" = length(intersect(set_a, set_b)),
                  "jacard"    = jacard(set_a, set_b),
                  "set_sizes" = length(set_b),
                  "tot_int"   = tot_int))
    }
  })
  inter_vals <- lapply(vals, function(v){v$"intersect"}) %>% unlist()
  set_sizes  <- c(length(DCM$it_sets[[1]]), unlist(lapply(vals, function(v){v$"set_sizes"})))
  jac_vals   <- lapply(vals, function(v){v$"jacard"}) %>% unlist()
  tot_int <- vals[[length(vals)]]$"tot_int"
  
  # Make plots.
  ## Plot intersection sizes.
  plot(x=(1:(length(DCM$it_sets)-1))+0.5,
       y=inter_vals, 
       main=paste0("Search ", i),
       xlab="Iteration", 
       ylab="Size",
       ylim=c(0, 3000),
       pch=4,
       type="b")
  ## Adding set sizes
  lines(x=1:length(DCM$it_sets), y=set_sizes, lty=2)
  points(x=1:length(DCM$it_sets), y=set_sizes, pch=16)
  ## Adding total intersection line.
  abline(h=tot_int)
  
  ## Plot Jaccard indices.
  plot(x=(1:(length(DCM$it_sets)-1))+0.5, 
       y=jac_vals, 
       main="Jaccard Index",
       xlab="Iteration",
       ylab="Jaccard Index",
       ylim=c(0, 1),
       type="l")
})
```