---
title: "DCM Analysis LumA vs. LumB"
author: "Kevin O'Connor"
date: "7/3/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries and directories.
library(dplyr)
data.dir <- file.path("/Users/kevinoconnor/Documents/Research/DCM/2018_06_10 19_33_33")
```

```{r dcm_5, echo=FALSE}
jacard <- function(a, b){
  length(intersect(a, b))/length(union(a, b))
}

load(file.path(data.dir, paste0("Debug_Output/Initialization.RData")))
init_set <- length(initialization$"found")
no_output <- lapply(1:5, function(i){
  load(file.path(data.dir, paste0("Debug_Output/DCM_", i, ".RData")))
  
  # Iterate through consecutive sets and record intersections and jacards.
  tot_int <- DCM$it_sets[[1]]
  vals <- lapply(1:(length(DCM$it_sets)-1), function(j){
    # Store first and second sets.
    set_a <- DCM$it_sets[[j]]
    set_b <- DCM$it_sets[[j+1]]
    
    # Update total intersection.
    tot_int <- length(intersect(tot_int, set_b))
    
    # Return relevant information.
    if(j < (length(DCM$it_sets)-1)){
      return(list("intersect" = length(intersect(set_a, set_b)),
                  "jacard"    = jacard(set_a, set_b),
                  "set_sizes" = length(set_b)))
    } else {
      return(list("intersect" = length(intersect(set_a, set_b)),
                  "jacard"    = jacard(set_a, set_b),
                  "set_sizes" = length(set_b),
                  "tot_int"   = tot_int))
    }
  })
  inter_vals <- lapply(vals, function(v){v$"intersect"}) %>% unlist()
  set_sizes  <- c(length(DCM$it_sets[[1]]), unlist(lapply(vals, function(v){v$"set_sizes"})))
  jac_vals   <- lapply(vals, function(v){v$"jacard"}) %>% unlist()
  tot_int <- vals[[length(vals)]]$"tot_int"
  
  # Make plots.
  ## Plot intersection sizes.
  plot(x=(1:(length(DCM$it_sets)-1))+0.5,
       y=inter_vals, 
       main=paste0("Search ", i),
       xlab="Iteration", 
       ylab="Size",
       xlim=c(1, 11),
       ylim=c(0,3000),
       pch=4,
       type="b")
  axis(side=1, at=1:length(DCM$it_sets))
  ## Adding set sizes
  lines(x=1:length(DCM$it_sets), y=set_sizes, lty=2)
  points(x=1:length(DCM$it_sets), y=set_sizes, pch=16)
  ## Adding total intersection line.
  abline(h=tot_int)
  ## Adding Jacard indices.
  ###par(new=TRUE)
  ###plot(x=(1:(length(DCM$it_sets)-1))+0.5, y=jac_vals, type="l", lty=3, ylim=c(0, 1), yaxt='n', xaxt='n', ann=FALSE)
  ###points(x=(1:(length(DCM$it_sets)-1))+0.5, y=jac_vals, pch=2, ylab="Jacard Index")
  ###axis(side=4, at=seq(0, 1, by=0.1))
  ###legend(x="bottomright", legend=c("Set Size", "Intersection Size", "Jacard Index"), pch=c(16, 4, 2))
  legend(x="bottomright", legend=c("Set Size", "Intersection Size"), pch=c(16, 4))
})
```
